all:
	sudo dnf install vim
	sudo dnf install httpd
	sudo dnf install perl
	sudo dnf install perl-libwww-perl
	sudo dnf install perl-LWP-Online
	sudo dnf install perl-LWP-Protocol-http10
	sudo dnf install perl-LWP-Protocol-https
	sudo dnf install perl-LWP-Authen-Negotiate
	sudo dnf install perl-LWP-Authen-Wsse
	sudo dnf install perl-LWP-Protocol-connect
	sudo dnf install perl-LWP-UserAgent-DNS-Hosts
	sudo dnf install perl-LWP-UserAgent-Determined
	sudo dnf install perl-LWP-Protocol-PSGI
	sudo dnf install perl-DBI
	sudo dnf install perl-DBD-MySQL
	sudo dnf install php
	sudo dnf install php-pdo
	sudo dnf install php-pdo-dblib
	sudo dnf install python
	sudo dnf install ruby

