all: 
	@echo "Use Fedora" --assumeyes
fedora: 
	sudo dnf install vim -y --assumeyes
	sudo dnf install httpd --assumeyes
	sudo dnf install perl --assumeyes
	sudo dnf install perl-libwww-perl --assumeyes
	sudo dnf install perl-LWP-Online --assumeyes
	sudo dnf install perl-LWP-Protocol-http10 --assumeyes
	sudo dnf install perl-LWP-Protocol-https --assumeyes
	sudo dnf install perl-LWP-Authen-Negotiate --assumeyes
	sudo dnf install perl-LWP-Authen-Wsse --assumeyes
	sudo dnf install perl-LWP-Protocol-connect --assumeyes
	sudo dnf install perl-LWP-UserAgent-DNS-Hosts --assumeyes
	sudo dnf install perl-LWP-UserAgent-Determined --assumeyes
	sudo dnf install perl-LWP-Protocol-PSGI --assumeyes
	sudo dnf install perl-DBI --assumeyes
	sudo dnf install perl-DBD-MySQL --assumeyes
	sudo dnf install php --assumeyes
	sudo dnf install php-pdo --assumeyes
	sudo dnf install php-pdo-dblib --assumeyes
	sudo dnf install python --assumeyes
	sudo dnf install pip --assumeyes
	sudo dnf install ruby --assumeyes
	wget https://dev.mysql.com/get/mysql80-community-release-fc27-1.noarch.rpm 
	sudo rpm -ivh mysql80-community-release-fc27-1.noarch.rpm 
	sudo dnf install mysql-community-server --assumeyes
	sudo dnf install mysql-community-libs --assumeyes
	sudo dnf install mysql-community-common --assumeyes
	sudo dnf install mysql-community-client --assumeyes
	sudo dnf install mysql-community-devel --assumeyes
#	sudo dnf install mysql-community-embedded --assumeyes
#	sudo dnf install mysql-community-embedded-devel --assumeyes
	sudo dnf install mysql-community-test --assumeyes
	sudo dnf install mysql-shell --assumeyes
	sudo dnf install mysql-shell-debuginfo --assumeyes
	sudo dnf install mysql-utilities --assumeyes
	sudo dnf install mysql-workbench-community --assumeyes
	sudo dnf install mysql-workbench-community-debuginfo --assumeyes
	sudo dnf install mysql-router --assumeyes
	sudo dnf install mysql-router-debuginfo --assumeyes
	sudo dnf install mysql-router-debugsource --assumeyes
	sudo dnf install mysql-connector-python --assumeyes
	sudo dnf install mysql-connector-python-cext --assumeyes
	sudo dnf install mysql-connector-python-debuginfo --assumeyes
	sudo dnf install mysql-connector-python3 --assumeyes
	sudo dnf install mysql-connector-python3-cext --assumeyes
	sudo dnf install mysql-connector-odbc-setup --assumeyes
	sudo dnf install mysql-connector-odbc-setup-debuginfo --assumeyes
	sudo dnf install mysql-connector-odbc-debuginfo --assumeyes
	sudo dnf install mysql-connector-odbc-debugsource --assumeyes
	sudo dnf install mysql-connector-odbc-test --assumeyes
	sudo pip install awscli --upgrade --user 
